
@startmindmap
* Standard Library groupings
** C4 (does not contain sprites)
** Sprites
*** Sprites only
**** logos
**** cloudinsight
**** kubernetes
*** Sprites and Macros
**** Type 1
***** aws (origina)
****** osa
****** elastic
**** Type 2
***** azure
****** awslib (newest)
**** Type 3
***** office
***** tupadr3
****** cloudogu
**** Type 4
***** material
@endmindmap
