'diagram from https://plantuml.com/creole
@startuml
:* You can change <color:red>text color</color>
* You can change <back:cadetblue>background color</back>
* You can change <size:18>size</size>
* You use <u>legacy</u> <b>HTML <i>tag</i></b>
* You use <u:red>color</u> <s:green>in HTML</s> <w:#0000FF>tag</w>
----
* image x0.5 : <img:http://plantuml.com/logo3.png{scale=0.5}>
----
* image x1.5 : <img:http://plantuml.com/logo3.png{scale=1.5}>
;
@enduml

