@startuml

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml
!include osaPuml/Hardware/all.puml
!include osaPuml/Misc/all.puml
!include osaPuml/Server/all.puml
!include osaPuml/Site/all.puml


' Users
osa_user_green_developer(osa_user_green_developer, "label", "tech")
osa_user_green_operations(osa_user_green_operations, "label", "tech")
osa_user_green_business_manager(osa_user_green_business_manager, "label", "tech")

' Devices
osa_desktop(osa_desktop, "label", "tech")
osa_laptop(osa_laptop, "label", "tech")
osa_iPhone(osa_iPhone, "label", "tech")
osa_server(osa_server, "label", "tech")

' Network
osa_device_wireless_router(osa_device_wireless_router, "label", "tech")
osa_hub(osa_hub, "label", "tech")
osa_firewall(osa_firewall, "label", "tech")
osa_cloud(osa_cloud, "label", "tech")

footer %filename() rendered with PlantUML version %version()\nThe Hitchhiker’s Guide to PlantUML
@enduml


