@startuml

'left to right direction
'top to bottom direction

'skinparam nodesep 10
skinparam ranksep 150

rectangle Arrows
rectangle A
rectangle B
rectangle C
rectangle D
rectangle E
rectangle F

Arrows -[bold]-> A 
Arrows -[#pink,dashed,thickness=10]-> B
Arrows -[#4567ff,dotted]-> C
Arrows --> D

'long arrow for no good reason 
E ---> C 

@enduml